/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2018-03-05 07:43:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/finalProject/finalPro/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1519985674000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Basic Page Needs\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<title>Travel Stargram</title>\r\n");
      out.write("\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Mobile Specific Metas\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- CSS\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/base.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/skeleton.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/layout.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/font-awesome.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/retina.css\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/animsition.min.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- Favicons\r\n");
      out.write("\t================================================== -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"apple-touch-icon-72x72.png\">\r\n");
      out.write("\t<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"apple-touch-icon-114x114.png\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("<div class=\"animsition\">\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<!-- Primary Page Layout\r\n");
      out.write("\t================================================== -->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"cd-section\">\r\n");
      out.write("\t\t<div class=\"cd-block\">\r\n");
      out.write("\t\t\t<div class=\"about-top\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"big-text-pages-top\">\r\n");
      out.write("\t\t\t\t\t<h1>Based in Serbia<span>.</span></h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"small-text\">- we craft beautiful digital solutions -</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"#scroll-link\" class=\"scroll scroll-down\"></a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section> <!-- .cd-section --> \r\n");
      out.write("\r\n");
      out.write("\t<section class=\"section white-background padding-top-bottom shadow-sec\" id=\"scroll-link\">\r\n");
      out.write("\t\t<div class=\"container\">\t\r\n");
      out.write("\t\t\t<div class=\"eight columns\">\t\r\n");
      out.write("\t\t\t\t<div class=\"section-big-header-text\">\t\r\n");
      out.write("\t\t\t\t\t<h2>Original ideas into digital work<span>.</span></h2>\t\r\n");
      out.write("\t\t\t\t\t<div class=\"line-big-header\"></div>\r\n");
      out.write("\t\t\t\t\t<p>We believe in coming up with original ideas and turning them into digital work that is both innovative and measurable.</p> \r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<div class=\"eight columns\">\t\r\n");
      out.write("\t\t\t\t<p class=\"text-bottom-margin\">We carry a passion for performance marketing and have a knack for untangling even the toughest of knots.</p> \r\n");
      out.write("\t\t\t\t<p class=\"text-bottom-margin\">We are relentless in moving boundaries and carry out this spirited attitude into digital solutions. Digital solutions that engage, inspire and make you think. Make you curious.</p>\t\r\n");
      out.write("\t\t\t\t<p>Taking on thought-provoking projects that challenge us creatively and make us go the extra mile is what we consider a way of life.</p>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"section white-background padding-bottom hidden-sec\">\r\n");
      out.write("\t\t<div class=\"container\">\t\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\">\t\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>Alex Andrews</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>founder</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"skills-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Branding and Identity</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Interaction Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Product Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Website Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf099;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf09b;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf0d5;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team2.jpg\" alt=\"\">\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>Kara Kulis</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>development</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"skills-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Agile Development</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Website Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Mobile UI Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Branding and Identity</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf099;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf09b;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf0d5;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\">\t\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>Frank Furius</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>art director</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"skills-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Branding and Identity</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Interaction Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Product Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Website Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf099;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf09b;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf0d5;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"four columns\">\t\r\n");
      out.write("\t\t\t\t\t<div class=\"team-wrap\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/team4.jpg\" alt=\"\">\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mask-team\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>Iva Doe</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p><span>development</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"skills-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Agile Development</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Website Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Branding and Identity</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p><span>&#xf1db;</span>Mobile UI Design</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"list-social-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf099;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf09b;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"icon-soc-team\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">&#xf0d5;</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"section white-background padding-bottom hidden-sec\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"sixteen columns\">\r\n");
      out.write("\t\t\t\t<div class=\"section-header-text-left\">\r\n");
      out.write("\t\t\t\t\t<h4>Our services<span>.</span></h4> \r\n");
      out.write("\t\t\t\t\t<p>Our passion for perfection.</p> \r\n");
      out.write("\t\t\t\t\t<div class=\"line-header\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf109;</span> Design</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p> \r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf121;</span> Development</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf03e;</span> Photography</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf0c3;</span> Branding</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\t\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf008;</span> Motion</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p> \r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf08e;</span> UX / UI</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p> \r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf0a1;</span> Marketing</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p> \r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"four columns\">\r\n");
      out.write("\t\t\t\t<div class=\"services-box\">\r\n");
      out.write("\t\t\t\t\t<h6><span>&#xf086;</span> 24/7 Support</h6>\r\n");
      out.write("\t\t\t\t\t<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation.</p> \r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- JAVASCRIPT\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\t\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modernizr.custom.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.animsition.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("(function($) { \"use strict\";\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t  \r\n");
      out.write("\t  $(\".animsition\").animsition({\r\n");
      out.write("\t  \r\n");
      out.write("\t\tinClass               :   'zoom-in-sm',\r\n");
      out.write("\t\toutClass              :   'zoom-out-sm',\r\n");
      out.write("\t\tinDuration            :    800,\r\n");
      out.write("\t\toutDuration           :    800,\r\n");
      out.write("\t\tlinkElement           :   '.animsition-link', \r\n");
      out.write("\t\t// e.g. linkElement   :   'a:not([target=\"_blank\"]):not([href^=#])'\r\n");
      out.write("\t\tloading               :    true,\r\n");
      out.write("\t\tloadingParentElement  :   'body', //animsition wrapper element\r\n");
      out.write("\t\tloadingClass          :   'animsition-loading',\r\n");
      out.write("\t\tunSupportCss          : [ 'animation-duration',\r\n");
      out.write("\t\t\t\t\t\t\t\t  '-webkit-animation-duration',\r\n");
      out.write("\t\t\t\t\t\t\t\t  '-o-animation-duration'\r\n");
      out.write("\t\t\t\t\t\t\t\t],\r\n");
      out.write("\t\t//\"unSupportCss\" option allows you to disable the \"animsition\" in case the css property in the array is not supported by your browser. \r\n");
      out.write("\t\t//The default setting is to disable the \"animsition\" in a browser that does not support \"animation-duration\".\r\n");
      out.write("\t\t\r\n");
      out.write("\t\toverlay               :   false,\r\n");
      out.write("\t\t\r\n");
      out.write("\t\toverlayClass          :   'animsition-overlay-slide',\r\n");
      out.write("\t\toverlayParentElement  :   'body'\r\n");
      out.write("\t  });\r\n");
      out.write("\t});  \r\n");
      out.write("})(jQuery);\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/retina-1.1.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/classie.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cbpAnimatedHeader.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/menu.js\"></script> \t\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/scroll.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/custom-about.js\"></script>  \t  \r\n");
      out.write("<!-- End Document\r\n");
      out.write("================================================== -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /about.jsp(44,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /about.jsp(291,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
